apiVersion: k8s.otterize.com/v2beta1
kind: KafkaServerConfig
metadata:
  name: kafkaserverconfig
  namespace: otterize-ecom-kafka-demo
spec:
  workload:
    name: kafka
  addr: kafka-headless.otterize-ecom-kafka-demo:9092
  tls:
    certFile: /etc/otterize-spire/cert.pem
    keyFile: /etc/otterize-spire/key.pem
    rootCAFile: /etc/otterize-spire/ca.pem
  topics:
    - topic: "*"
      pattern: literal
      clientIdentityRequired: false
      intentsRequired: false