apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: orderservice
spec:
  service:
    name: orderservice
  calls:
    - name: kafka
      type: kafka
      kafkaTopics:
        - name: orders
          operations: [ consume ]
    - name: emailservice
