apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: paymentservice
spec:
  service:
    name: paymentservice
  calls:
    - name: kafka
      type: kafka
      kafkaTopics:
        - name: payments
          operations: [ produce ]
