apiVersion: v1
kind: Namespace
metadata:
  name: otterize-tutorial-kafka-mtls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: otterize-tutorial-kafka-mtls
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        credentials-operator.otterize.com/tls-secret-name: client-credentials-secret
        credentials-operator.otterize.com/cert-file-name: "tls.crt"
        credentials-operator.otterize.com/key-file-name: "tls.key"
        credentials-operator.otterize.com/ca-file-name: "ca.crt"
    spec:
      containers:
        - name: client
          image: santafen/otterize-kafka-client:1.0.9
          command: [ "/bin/sh", "-c", "cd /app/client;./client" ]
          volumeMounts:
            - name: otterize-credentials
              mountPath: /var/otterize/credentials
              readOnly: true
      volumes:
        - name: otterize-credentials
          secret:
            secretName: client-credentials-secret
            items:
              - key: tls.crt
                path: cert.pem
              - key: tls.key
                path: key.pem
              - key: ca.crt
                path: ca.pem
        - name: ephemeral
          emptyDir: { }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-other
  namespace: otterize-tutorial-kafka-mtls
spec:
  selector:
    matchLabels:
      app: client-other
  template:
    metadata:
      labels:
        app: client-other
      annotations:
        credentials-operator.otterize.com/tls-secret-name: client-other-credentials-secret
        credentials-operator.otterize.com/cert-file-name: "tls.crt"
        credentials-operator.otterize.com/key-file-name: "tls.key"
        credentials-operator.otterize.com/ca-file-name: "ca.crt"
    spec:
      containers:
        - name: client-other
          image: santafen/otterize-kafka-client:1.0.9
          command: [ "/bin/sh", "-c", "cd /app/client-other;./client-other" ]
          volumeMounts:
            - name: otterize-credentials
              mountPath: /var/otterize/credentials
              readOnly: true
      volumes:
        - name: otterize-credentials
          secret:
            secretName: client-other-credentials-secret
            items:
              - key: tls.crt
                path: cert.pem
              - key: tls.key
                path: key.pem
              - key: ca.crt
                path: ca.pem
        - name: ephemeral
          emptyDir: { }
