apiVersion: k8s.otterize.com/v2beta1
kind: KafkaServerConfig
metadata:
  name: kafkaserverconfig
  namespace: kafka
spec:
  workload:
    name: kafka
  addr: kafka.kafka:9092
  tls:
    certFile: /etc/otterize-spire/cert.pem
    keyFile: /etc/otterize-spire/key.pem
    rootCAFile: /etc/otterize-spire/ca.pem
  topics:
    - topic: "transactions"
      pattern: literal
      clientIdentityRequired: true
      intentsRequired: false
    - topic: "mytopic"
      pattern: literal
      clientIdentityRequired: true
      intentsRequired: false
