apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: kafka
  namespace:  kafka
spec:
  workload:
    name: kafka
    kind: StatefulSet
  targets:
    - service:
        name: kafka.kafka-zookeeper
