apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: cartservice
  namespace: otterize-visual-tutorial-istio
spec:
  workload:
    name: cartservice
    kind: Deployment
  targets:
    - service:
        name: redis-cart
        http:
          - path: /items
            methods:
              - GET
              - POST