apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: checkoutservice
  namespace: otterize-visual-tutorial-istio
spec:
  service:
    name: checkoutservice
  calls:
    - name: productcatalogservice
      type: http
      resources:
        - path: /products
          methods:
            - POST