apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: checkoutservice
  namespace: otterize-visual-tutorial-istio
spec:
  workload:
    name: checkoutservice
    kind: Deployment
  targets:
    - service:
        name: productcatalogservice
        http:
          - path: /products
            methods:
              - POST