apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: frontend
  namespace: otterize-visual-tutorial-istio
spec:
  workload:
    name: frontend
    kind: Deployment
  targets:
    - service:
        name: adservice
        http:
          - path: /ads
            methods:
              - GET
    - service:
        name: cartservice
        http:
          - path: /items
            methods:
              - POST
              - GET
    - service:
        name: checkoutservice
        http:
          - path: /checkout
            methods:
              - POST
    - service:
        name: currencyservice
        http:
          - path: /currency
            methods:
              - GET
    - service:
        name: productcatalogservice
        http:
          - path: /products
            methods:
              - GET
    - service:
        name: recommendationservice
        http:
          - path: /recommendations
            methods:
              - GET
    - service:
        name: shippingservice
        http:
          - path: /shipping
            methods:
              - POST