apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: loadgenerator
  namespace: otterize-visual-tutorial-istio
spec:
  workload:
    name: loadgenerator
    kind: Deployment
  targets:
    - service:
        name: frontend
        http:
          - path: /
            methods:
              - GET