apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: loadgenerator
  namespace: otterize-visual-tutorial-istio
spec:
  service:
    name: loadgenerator
  calls:
    - name: frontend
      type: http
      resources:
        - path: /
          methods:
            - GET