apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: recommendationservice
  namespace: otterize-visual-tutorial-istio
spec:
  workload:
    name: recommendationservice
    kind: Deployment
  targets:
    - service:
        name: productcatalogservice
        http:
          - path: /similar-products
            methods:
              - GET