apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: server
  namespace: otterize-tutorial-gcp-iam
spec:
  service:
    name: server
  calls:
    - name: projects/_/buckets/otterize-tutorial-bucket*
      type: gcp
      gcpPermissions:
        - "storage.admin"