apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: server
  namespace: otterize-tutorial-gcp-iam
spec:
  workload:
    name: server
    kind: Deployment
  calls:
    - gcp:
        resource: projects/_/buckets/otterize-tutorial-bucket*
        permissions:
          - "storage.admin"