apiVersion: v1
kind: Namespace
metadata:
  name: otterize-tutorial-gcp-iam
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
  namespace: otterize-tutorial-gcp-iam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: otterize-tutorial-gcp-iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          imagePullPolicy: Always
          image: 'public.ecr.aws/e3b4k2v5/gcp-tutorial:client'
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: otterize-tutorial-gcp-iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccountName: server
      containers:
        - name: server
          imagePullPolicy: Always
          image: 'public.ecr.aws/e3b4k2v5/gcp-tutorial:server'
          ports:
            - containerPort: 80
          env:
            - name: BUCKET_NAME
              value: "otterize-demo-bucket"
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: otterize-tutorial-gcp-iam
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - name: http
      port: 80
      targetPort: 80