apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: psql-client
spec:
  workload:
    name: psql-client
    kind: CronJob
  targets:
    - sql:
        name: otterize-tutorial-cloudsql # note: this name should be the same as your database integration's name
        privileges:
          - databaseName: otterize_tutorial
            table:
            operations: