apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: client-intents-for-server
  namespace: otterize-tutorial-postgres
spec:
  workload:
    name: server
    kind: Deployment
  targets:
    - sql:
        name: postgres-tutorial-db # Same name as our PostgreSQLServerConfig metadata.name
        privileges:
          - databaseName: otterize-tutorial
            table: public.example
            operations:
              - SELECT
              - INSERT