apiVersion: k8s.otterize.com/v2alpha1
kind: PostgreSQLServerConfig
metadata:
  name: postgres-tutorial-db
spec:
  address: database.otterize-tutorial-postgres.svc.cluster.local:5432
  credentials:
    secretRef:
      name: postgres-tutorial-db-credentials