apiVersion: k8s.otterize.com/v1alpha3
kind: PostgreSQLServerConfig
metadata:
  name: postgres-tutorial-db
spec:
  address: database.otterize-tutorial-postgres.svc.cluster.local:5432
  credentials:
    secretRef:
      name: postgres-tutorial-db-credentials
---
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: postgres-tutorial-db-credentials
data:
  username: '' # Your PostgreSQL server user
  password: '' # Your PostgreSQL server password