apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: cartservice
  namespace: otterize-visual-tutorial-istio
spec:
  workload:
    name: cartservice
    kind: Deployment
  targets:
    - service:
        name: redis-cart
        http:
          - path: /items
            methods:
              - GET
              - POST
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: checkoutservice
  namespace: otterize-visual-tutorial-istio
spec:
  workload:
    name: checkoutservice
    kind: Deployment
  targets:
    - service:
        name: productcatalogservice
        http:
          - path: /products
            methods:
              - POST
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: frontend
  namespace: otterize-visual-tutorial-istio
spec:
  workload:
    name: frontend
    kind: Deployment
  targets:
    - service:    
        name: adservice
        http:
          - path: /ads
            methods:
              - GET
    - service:
        name: cartservice
        http:
          - path: /items
            methods:
              - GET
              - POST
    - service:
        name: checkoutservice
        http:
          - path: /checkout
            methods:
              - POST
    - service:
        name: currencyservice
        http:
          - path: /currency
            methods:
              - GET
    - service:
        name: productcatalogservice
        http:
          - path: /products
            methods:
              - GET
    - service:
        name: recommendationservice
        http:
          - path: /recommendations
            methods:
              - GET
    - service:
        name: shippingservice
        http:
          - path: /shipping
            methods:
              - POST
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: loadgenerator
  namespace: otterize-visual-tutorial-istio
spec:
  workload:
    name: loadgenerator
    kind: Deployment
  targets:
    - service:
        name: frontend
        http:
          - path: /
            methods:
              - GET
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: recommendationservice
  namespace: otterize-visual-tutorial-istio
spec:
  workload:
    name: recommendationservice
    kind: Deployment
  targets:
    - service:
        name: productcatalogservice
        http:
          - path: /similar-products
            methods:
              - GET