apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: client
  namespace: otterize-tutorial-istio
spec:
  service:
    name: client
  calls:
    - name: nginx
      type: http
      resources:
        - path: /client-path
          methods: [ GET ]