apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: frontend
spec:
  workload:
    name: frontend
    kind: Deployment
  targets:
    - service:
        name: recommendationservice
        http:
          - path: /recommendations
            methods:
              - GET
    - service:
        name: productcatalogservice
        http:
          - path: /products
            methods:
              - GET