apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: myclient
  namespace:  ibac-for-kafka
spec:
  workload:
    name: myclient
    kind: Deployment
  targets:
    - kafka:
        name: kafka.kafka
        topics:
          - name: my-topic
            operations: [ all ]
