apiVersion: v1
kind: Namespace
metadata:
  name: ibac-for-kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interactive
  namespace: ibac-for-kafka
spec:
  selector:
    matchLabels:
      app: interactive
  template:
    metadata:
      labels:
        app: interactive
    spec:
      containers:
        - name: interactive
          image: bitnami/kafka
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "sleep infinity" ]
