apiVersion: k8s.otterize.com/v1alpha2
kind: KafkaServerConfig
metadata:
  name: kafkaserverconfig
  namespace: kafka
spec:
  service:
    name: kafka
  addr: kafka.kafka:9092
  tls:
    certFile: /etc/otterize-spire/svid.pem
    keyFile: /etc/otterize-spire/key.pem
    rootCAFile: /etc/otterize-spire/bundle.pem
  topics:
    - topic: "*"
      pattern: prefix
      clientIdentityRequired: false
      intentsRequired: false
    - topic: "my-topic"
      pattern: literal
      clientIdentityRequired: true
      intentsRequired: false
    - topic: "my-topic-intended"
      pattern: literal
      clientIdentityRequired: true
      intentsRequired: true