apiVersion: apps/v1
kind: Deployment
metadata:
  name: joketrainer
  namespace: otterize-tutorial-aws-visibility
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joketrainer
  template:
    metadata:
      labels:
        app: joketrainer
        network-mapper.otterize.com/aws-visibility: "true"
    spec:
      containers:
        - name: joketrainer
          image: otterize/aws-visibility-tutorial:latest
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: DAD_JOKE_LAMBDA_ARN
              valueFrom:
                configMapKeyRef:
                  name: lambda-arns
                  key: dadJokeLambdaArn
            - name: FEEDBACK_LAMBDA_ARN
              valueFrom:
                configMapKeyRef:
                  name: lambda-arns
                  key: feedbackLambdaArn
