apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: server
spec:
  workload:
    name: joketrainer
  targets:
    - aws:
        arn: arn:aws:lambda:us-west-2:*:function:OtterizeTutorialJokeTrainingStack-*
        actions:
          - "lambda:InvokeFunction"