apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: server
spec:
  workload:
    name: server
    kind: Deployment
  targets:
    - aws:
        arn: arn:aws:s3:::otterize-tutorial-bucket-*/*
        actions:
          - "s3:PutObject"