apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: client-intents-for-client
  namespace: otterize-tutorial-azure-iam
spec:
  workload:
    name: client
    kind: Deployment
  targets:
    - azure:
        scope: /providers/Microsoft.Storage/storageAccounts/STORAGE_ACCOUNT_NAME/blobServices/default/containers/downloads
        dataActions:
          - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read
    - azure:
        scope: /providers/Microsoft.Storage/storageAccounts/STORAGE_ACCOUNT_NAME/blobServices/default/containers/uploads
        dataActions:
          - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/add/action
          - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write
