apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: client
  namespace: otterize-tutorial-istio
spec:
  workload:
    name: client
    kind: Deployment
  targets:
    - service:
        name: nginx-service
        http:
          - path: /client-path
            methods: [ GET ]