apiVersion: v1
kind: Namespace
metadata:
  name: ibac-for-kafka
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: interactive-properties
  namespace: ibac-for-kafka
data:
  client.properties: |
    security.protocol=SSL
    ssl.keystore.location=/var/otterize/credentials/kafka.keystore.jks
    ssl.keystore.password=password
    ssl.truststore.location=/var/otterize/credentials/kafka.truststore.jks
    ssl.truststore.password=password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interactive
  namespace: ibac-for-kafka
spec:
  selector:
    matchLabels:
      app: interactive
  template:
    metadata:
      labels:
        app: interactive
      annotations:
        credentials-operator.otterize.com/tls-secret-name: interactive-credentials-secret
        credentials-operator.otterize.com/cert-type: jks
        credentials-operator.otterize.com/truststore-file-name: kafka.truststore.jks
        credentials-operator.otterize.com/keystore-file-name: kafka.keystore.jks
    spec:
      containers:
        - name: interactive
          image: bitnami/kafka
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "sleep infinity" ]
          volumeMounts:
            - mountPath: /app
              name: interactive-properties
            - name: otterize-credentials
              mountPath: /var/otterize/credentials
              readOnly: true
      volumes:
        - name: interactive-properties
          configMap:
            name: interactive-properties
        - name: otterize-credentials
          secret:
            secretName: interactive-credentials-secret
            items:
              - key: truststore.jks
                path: kafka.truststore.jks
              - key: keystore.jks
                path: kafka.keystore.jks