apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: interactive
  namespace:  ibac-for-kafka
spec:
  workload:
    name: interactive
    kind: Deployment
  targets:
    - kafka:
        name: kafka.kafka
        topics:
          - name: my-topic-intended
            operations: [ all ]
