apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-other
  namespace: otterize-tutorial-kafka-mtls
spec:
  selector:
    matchLabels:
      app: client-other
  template:
    metadata:
      labels:
        app: client-other
      annotations:
        credentials-operator.otterize.com/tls-secret-name: client-other-credentials-secret
    spec:
      containers:
        - name: client-other
          image: golang
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do cd /app; cp src/* .; go get main; go run .; sleep infinity; done" ]
          volumeMounts:
            - name: ephemeral
              mountPath: /app
            - mountPath: /app/src
              name: client-other-go
            - name: otterize-credentials
              mountPath: /var/otterize/credentials
              readOnly: true
      volumes:
        - name: client-other-go
          configMap:
            name: client-other-go
        - name: otterize-credentials
          secret:
            secretName: client-other-credentials-secret
        - name: ephemeral
          emptyDir: { }