apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: myclient
  namespace:  otterize-tutorial-kafka-mtls
spec:
  service:
    name: myclient
  calls:
    - name: kafka.kafka
      type: kafka
      topics:
        - name: mytopic
          operations: [ all ]
