apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: client
  namespace: otterize-tutorial-kafka-mtls
spec:
  workload:
    name: client
    kind: Deployment
  targets:
    - kafka:
        name: kafka.kafka
        topics:
          - name: mytopic
            operations: [ produce,describe,consume ]
          - name: transactions
            operations: [ produce,describe,consume ]
---
apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: kafka
  namespace: kafka
spec:
  workload:
    name: kafka
    kind: StatefulSet
  targets:
    - kubernetes:
        name: kafka
        kind: StatefulSet
    - service:
        name: kafka-zookeeper

