apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: client
  namespace:  otterize-tutorial-npol
spec:
  workload:
    name: client
  targets:
    - service:
        name: server