apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: cartservice
spec:
  workload:
    name: cartservice
    kind: Deployment
  targets:
    - service:
        name: redis-cart
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: checkoutservice
spec:
  workload:
    name: checkoutservice
    kind: Deployment
  targets:
    - service:
        name: cartservice
    - service:
        name: currencyservice
    - service:
        name: emailservice
    - service:
        name: kafka
    - service:
        name: paymentservice
    - service:
        name: productcatalogservice
    - service:
        name: shippingservice

---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: frontend
spec:
  workload:
    name: frontend
    kind: Deployment
  targets:
    - service:
        name: adservice
    - service:
        name: cartservice
    - service:
        name: checkoutservice
    - service:
        name: currencyservice
    - service:
        name: productcatalogservice
    - service:
        name: recommendationservice
    - service:
        name: shippingservice
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: kafka
spec:
  workload:
    name: kafka
    kind: StatefulSet
  targets:
    - service:
        name: kafka
    - service:
        name: zookeeper
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: loadgenerator
spec:
  workload:
    name: loadgenerator
    kind: Deployment
  targets:
    - service:
        name: frontend
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: orderservice
spec:
  workload:
    name: orderservice
    kind: Deployment
  targets:
    - service:
        name: kafka
    - service:
        name: emailservice
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: paymentservice
spec:
  workload:
    name: paymentservice
    kind: Deployment
  targets:
    - service:
        name: kafka
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: recommendationservice
spec:
  workload:
    name: recommendationservice
    kind: Deployment
  targets:
    - service:
        name: productcatalogservice