apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: cartservice
spec:
  workload:
    name: cartservice
  targets:
    - service:
        name: redis-cart
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: checkoutservice
spec:
  workload:
    name: checkoutservice
  targets:
    - service:
        name: cartservice
    - service:
        name: currencyservice
    - service:
        name: emailservice
    - service:
        name: kafka
    - service:
        name: paymentservice
    - service:
        name: productcatalogservice
    - service:
        name: shippingservice

---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: frontend
spec:
  workload:
    name: frontend
  targets:
    - service:
        name: adservice
    - service:
        name: cartservice
    - service:
        name: checkoutservice
    - service:
        name: currencyservice
    - service:
        name: productcatalogservice
    - service:
        name: recommendationservice
    - service:
        name: shippingservice
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: kafka
spec:
  workload:
    name: kafka
  targets:
    - service:
        name: kafka
    - service:
        name: zookeeper
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: loadgenerator
spec:
  workload:
    name: loadgenerator
  targets:
    - service:
        name: frontend
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: orderservice
spec:
  workload:
    name: orderservice
  targets:
    - service:
        name: kafka
    - service:
        name: emailservice
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: paymentservice
spec:
  workload:
    name: paymentservice
  targets:
    - service:
        name: kafka
---
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: recommendationservice
spec:
  workload:
    name: recommendationservice
  targets:
    - service:
        name: productcatalogservice