apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: paymentservice
spec:
  workload:
    name: paymentservice
    kind: Deployment
  targets:
    - kafka:
        name: kafka
        topics:
          - name: payments
            operations: [ all ]
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: checkoutservice
spec:
  workload:
    name: checkoutservice
    kind: Deployment
  targets:
    - kafka:
        name: kafka
        topics:
          - name: orders
            operations: [ produce ]
    - service:
        name: cartservice
    - service:
        name: currencyservice
    - service:
        name: emailservice
    - service:
        name: paymentservice
    - service:
        name: productcatalogservice
    - service:
        name: shippingservice
---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: orderservice
spec:
  workload:
    name: orderservice
    kind: Deployment
  targets:
    - kafka:
        name: kafka
        topics:
          - name: orders
            operations: [ consume ]
    - service:
        name: emailservice