apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: paymentservice
spec:
  service:
    name: paymentservice
  calls:
    - name: kafka
      type: kafka
      topics:
        - name: payments
          operations: [ all ]
---
apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: checkoutservice
spec:
  service:
    name: checkoutservice
  calls:
    - name: kafka
      type: kafka
      topics:
        - name: orders
          operations: [ produce ]
    - name: cartservice
    - name: currencyservice
    - name: emailservice
    - name: paymentservice
    - name: productcatalogservice
    - name: shippingservice
---
apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: orderservice
spec:
  service:
    name: orderservice
  calls:
    - name: kafka
      type: kafka
      topics:
        - name: orders
          operations: [ consume ]
    - name: emailservice