apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: recommendationservice
spec:
  service:
    name: recommendationservice
  calls:
    - name: productcatalogservice
      type: http