apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: orderservice
spec:
  service:
    name: orderservice
  calls:
    - name: kafka
      type: kafka
      topics:
        - name: orders
          operations: [ consume ]
    - name: emailservice
