apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: checkoutservice
spec:
  service:
    name: checkoutservice
  calls:
    - name: kafka
      type: kafka
      kafkaTopics:
        - name: orders
          operations: [ produce ]
    - name: cartservice
    - name: currencyservice
    - name: emailservice
    - name: paymentservice
    - name: productcatalogservice
    - name: shippingservice