apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: orderservice
spec:
  workload:
    name: orderservice
    kind: Deployment
  targets:
    - kafka:
        name: kafka
        topics:
          - name: orders
            operations: [ consume ]
    - service:
        name: emailservice
