apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: paymentservice
spec:
  service:
    name: paymentservice
  calls:
    - name: kafka
      type: kafka
      topics:
        - name: payments
          operations: [ produce ]
