apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: frontend
spec:
  service:
    name: frontend
  calls:
    - name: recommendationservice
    - name: productcatalogservice
---
apiVersion: k8s.otterize.com/v1alpha2
kind: ClientIntents
metadata:
  name: checkoutservice
spec:
  service:
    name: checkoutservice
  calls:
    - name: productcatalogservice
