apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: recommendationservice
spec:
  workload:
    name: recommendationservice
    kind: Deployment
  targets:
    - service:
        name: productcatalogservice