apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: paymentservice
spec:
  workload:
    name: paymentservice
    kind: Deployment
  targets:
    - kafka:
        name: kafka
        topics:
          - name: payments
            operations: [ produce ]
