apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: client-intents-for-server
spec:
  workload:
    name: server
    kind: Deployment
  targets:
    - sql:
        name: mysql-tutorial-db
        privileges:
          - databaseName: otterize_example
            table: example
            operations:
            - SELECT
            - INSERT