apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: server
spec:
  service:
    name: server
  calls:
    - name: otterize-tutorial-mysql
      type: database
      databaseResources:
        - databaseName: otterize_example
          table: example
          operations:
            - SELECT
            - INSERT