apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: client-intents-for-server
spec:
  service:
    name: server
  calls:
    - name: mysql-tutorial-db
      type: database
      databaseResources:
        - databaseName: otterize_example
          table: example
          operations:
            - SELECT
            - INSERT