apiVersion: k8s.otterize.com/v2beta1
kind: MySQLServerConfig
metadata:
  name: mysql-tutorial-db
spec:
  address: mysql.otterize-tutorial-mysql.svc.cluster.local:3306 # Your MySQL server address
  credentials:
    secretRef:
      name: mysql-tutorial-db-credentials