apiVersion: k8s.otterize.com/v1alpha3
kind: MySQLServerConfig
metadata:
  name: mysql-tutorial-db
spec:
  address: database # Your MySQL server address
  credentials:
    username: admin # Your MySQL server user
    password: password # Your MySQL server password