apiVersion: v1
kind: Namespace
metadata:
  name: otterize-tutorial-mapper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: otterize-tutorial-mapper
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: alpine/curl
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do curl -si server; sleep 2; done" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: otterize-tutorial-mapper
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: hashicorp/http-echo
          args: [ "-listen=:80", "-text=\"hello world\""]
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: otterize-tutorial-mapper
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80