apiVersion: v1
kind: Namespace
metadata:
  name: otterize-tutorial-azure-iam
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: otterize-tutorial-azure-iam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: otterize-tutorial-azure-iam
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        azure.workload.identity/use: "true"
        credentials-operator.otterize.com/create-azure-workload-identity: "true"
    spec:
      serviceAccountName: client
      containers:
        - name: client
          image: mcr.microsoft.com/azure-cli
          command: [ "/bin/sh", "-c", "--" ]
          env:
            - name: AZURE_STORAGE_ACCOUNT
              value: otterizeazureiamtutorial
            - name: AZURE_STORAGE_CONTAINER
              value: otterizeazureiamtutorialcontainer
          args: [ "while true; do az login -o table --federated-token \"$(cat $AZURE_FEDERATED_TOKEN_FILE)\" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID; echo '\n'; az storage blob list --container $AZURE_STORAGE_CONTAINER --account-name $AZURE_STORAGE_ACCOUNT --auth-mode login -o table; sleep 1; echo '\nClient - The time is:' $(date) '\n'; sleep 2; done" ]