apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: client
  namespace: otterize-tutorial-azure-iam
spec:
  workload:
    name: client
    kind: Deployment
  targets:
    - azure:
        scope: "/providers/Microsoft.Storage/storageAccounts/ottrtutorial/blobServices/default/containers/ottrtutorialcontainer"
        roles:
          - "Storage Blob Data Contributor"
