apiVersion: v1
kind: Namespace
metadata:
  name: otterize-tutorial-azure-iam
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: otterize-tutorial-azure-iam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: otterize-tutorial-azure-iam
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        # Required by the Azure workload identity operator, only the pods with this label can use workload identity
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: client
      containers:
        - name: client
          image: mcr.microsoft.com/azure-cli
          command: [ "/bin/sh", "-c", "--" ]
          env:
            - name: STORAGE_ACCOUNT_NAME
              value: ottrazuredemo
          args:
            - while true;
              do
                echo;
                echo 'Client - The time is:' $(date);
                echo;
                if [[ -z "$AZURE_CLIENT_ID" ]]; then echo "Azure client ID not set";
                else
                  echo 'Logging in using federated identity credentials';
                  az login -o table --federated-token $(cat $AZURE_FEDERATED_TOKEN_FILE) --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID;
                  echo;
                  echo 'Downloading file from storage blob container downloads in storage account' $STORAGE_ACCOUNT_NAME;
                  az storage blob download --account-name $STORAGE_ACCOUNT_NAME -c downloads -n hello.txt --auth-mode login -o table;
                  echo 'Uploading file to storage blob container uploads in storage account' $STORAGE_ACCOUNT_NAME;
                  az storage blob upload --account-name $STORAGE_ACCOUNT_NAME --container-name uploads -n hello.txt --data "hello"  --overwrite --auth-mode login -o table;
                  echo;
                fi;
                sleep 5;
              done
