apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: otterize-tutorial-mtls
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        credentials-operator.otterize.com/tls-secret-name: client-credentials-secret
    spec:
      containers:
        - name: client
          image: node:19
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do node /app/client.js; sleep 2; done" ]
          volumeMounts:
            - mountPath: /app/
              name: client-js
            - name: otterize-credentials
              mountPath: /var/otterize/credentials
              readOnly: true
      volumes:
        - name: client-js
          configMap:
            name: client-js
        - name: otterize-credentials
          secret:
            secretName: client-credentials-secret