apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: frontend
  namespace:  otterize-tutorial-egress-access
spec:
  workload:
    name: frontend
    kind: Deployment
  targets:
    - service:
        name: backend

---
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: backend
  namespace: otterize-tutorial-egress-access
spec:
  workload:
    name: backend
    kind: Deployment
  targets:
    - service:
        name: frontend