apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
  name: myclient
  namespace:  ibac-for-kafka
spec:
  service:
    name: myclient
  calls:
    - name: kafka.kafka
      type: kafka
      kafkaTopics:
        - name: my-topic
          operations: [ all ]
