apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: checkoutservice
spec:
  workload:
    name: checkoutservice
    kind: Deployment
  targets:
    - service:
        name: emailservice
    - service:
        name: orderservice
        http:
          - path: /orders/*
            methods: [ get, post ]
    - kafka:
        topics:
          - name: orders
            operations: [ produce ]
