apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
  name: checkoutservice
  namespace:  otterize-ecom-demo
spec:
  workload:
    name: checkoutservice
  targets:
    - service:
        name: productcatalogservice