apiVersion: k8s.otterize.com/v1alpha1
kind: ClientIntents
metadata:
  name: checkoutservice
  namespace:  otterize-ecom-demo
spec:
  service:
    name: checkoutservice
  calls:
    - name: productcatalogservice