apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: cartservice
  namespace: otterize-ecom-demo
spec:
  workload:
    name: cartservice
    kind: Deployment
  targets:
    - service:
        name: redis-cart
---
apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: checkoutservice
  namespace: otterize-ecom-demo
spec:
  workload:
    name: checkoutservice
    kind: Deployment
  targets:
    - service:
        name: cartservice
    - service:
        name: currencyservice
    - service:
        name: emailservice
    - service:
        name: paymentservice
    - service:
        name: productcatalogservice
    - service:
        name: shippingservice
---
apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: frontend
  namespace: otterize-ecom-demo
spec:
  workload:
    name: frontend
    kind: Deployment
  targets:
    - service:
        name: adservice
    - service:
    -   name: cartservice
    - service:
    -   name: checkoutservice
    - service:
    -   name: currencyservice
    - service:
    -   name: productcatalogservice
    - service:
    -   name: recommendationservice
    - service:
    -   name: shippingservice
---
apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: loadgenerator
  namespace: otterize-ecom-demo
spec:
  workload:
    name: loadgenerator
    kind: Deployment
  targets:
    - service:
        name: frontend
---
apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: recommendationservice
  namespace: otterize-ecom-demo
spec:
  workload:
    name: recommendationservice
    kind: Deployment
  targets:
    - service:
        name: productcatalogservice
