apiVersion: k8s.otterize.com/v2beta1
kind: ClientIntents
metadata:
  name: recommendationservice
  namespace:  otterize-ecom-demo
spec:
  workload:
    name: recommendationservice
    kind: Deployment
  targets:
    - service:
        name: productcatalogservice