apiVersion: k8s.otterize.com/v1alpha1
kind: ClientIntents
metadata:
  name: recommendationservice
  namespace:  otterize-ecom-demo
spec:
  service:
    name: recommendationservice
  calls:
    - name: productcatalogservice
      type: HTTP